const $=id=>document.getElementById(id), numeric=['year','stint','games','atBats','runs','hits','doubles','triples','homeRuns','rbi','stolenBases','caughtStealing','walks','strikeouts','hitByPitch','sacrificeFlies'];
const labels={homeRuns:'Home runs',hits:'Hits',runs:'Runs',rbi:'RBI',stolenBases:'Stolen bases',walks:'Walks',strikeouts:'Strikeouts',battingAverage:'Batting average'};
let rows=[],charts={};
function parseCSV(text){const lines=text.trim().split(/\r?\n/),head=parseLine(lines.shift());return lines.map(line=>{const vals=parseLine(line),o={};head.forEach((h,i)=>o[h]=numeric.includes(h)?+(vals[i]||0):(vals[i]||''));return o})}
function parseLine(line){const out=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&quoted&&line[i+1]==='"'){value+='"';i++}else if(c==='"'){quoted=!quoted}else if(c===','&&!quoted){out.push(value);value=''}else value+=c}out.push(value);return out}
function unique(field){return [...new Set(rows.map(r=>r[field]).filter(Boolean))].sort((a,b)=>typeof a==='number'?a-b:a.localeCompare(b))}
function fillSelect(id,items,allLabel){const s=$(id);s.innerHTML=allLabel?`<option value="all">${allLabel}</option>`:'';items.forEach(v=>s.add(new Option(v,v)))}
const fmt=n=>new Intl.NumberFormat('en-US').format(n), avg=(h,ab)=>ab?h/ab:0;
function aggregate(data,field){const map=new Map();data.forEach(r=>{let key=field==='decade'?`${Math.floor(r.year/10)*10}s`:r[field]||'Unknown';if(!map.has(key))map.set(key,{key,rows:0,minYear:r.year,maxYear:r.year,atBats:0,hits:0,homeRuns:0,runs:0,rbi:0,stolenBases:0,walks:0,strikeouts:0});const x=map.get(key);x.rows++;x.minYear=Math.min(x.minYear,r.year);x.maxYear=Math.max(x.maxYear,r.year);['atBats','hits','homeRuns','runs','rbi','stolenBases','walks','strikeouts'].forEach(k=>x[k]+=r[k])});return [...map.values()].map(x=>({...x,battingAverage:avg(x.hits,x.atBats)}))}
function value(x,m){return x[m]||0}
function renderChart(id,type,items,labelField,measure,color,horizontal=false){if(charts[id])charts[id].destroy();charts[id]=new Chart($(id),{type,data:{labels:items.map(x=>x[labelField]),datasets:[{label:labels[measure],data:items.map(x=>value(x,measure)),backgroundColor:color,borderColor:color,borderWidth:type==='line'?2:0,tension:.2}]},options:{responsive:true,maintainAspectRatio:false,indexAxis:horizontal?'y':'x',plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{beginAtZero:measure!=='battingAverage',grid:{color:'rgba(16,43,78,.1)'}}}}})}
function update(){const start=+$('start-year').value,end=+$('end-year').value,team=$('team').value,league=$('league').value,q=$('player').value.trim().toLowerCase(),measure=$('measure').value,breakdown=$('breakdown').value;
 const data=rows.filter(r=>r.year>=start&&r.year<=end&&(team==='all'||r.teamName===team)&&(league==='all'||r.league===league)&&(!q||r.playerName.toLowerCase().includes(q)));
 const totals=aggregate(data,'league').reduce((a,x)=>{['rows','atBats','hits','homeRuns','runs','rbi','stolenBases','walks','strikeouts'].forEach(k=>a[k]+=x[k]);return a},{rows:0,atBats:0,hits:0,homeRuns:0,runs:0,rbi:0,stolenBases:0,walks:0,strikeouts:0});
 $('kpi-rows').textContent=fmt(data.length);$('kpi-players').textContent=fmt(new Set(data.map(r=>r.playerID)).size);$('kpi-total').textContent=measure==='battingAverage'?(avg(totals.hits,totals.atBats)).toFixed(3):fmt(totals[measure]||0);$('kpi-total-label').textContent=labels[measure];$('kpi-avg').textContent=avg(totals.hits,totals.atBats).toFixed(3).replace(/^0/,'');$('status').textContent=`Showing ${fmt(data.length)} of ${fmt(rows.length)} rows`;
 const yearly=aggregate(data,'year').sort((a,b)=>+a.key-+b.key),players=aggregate(data,'playerName').sort((a,b)=>value(b,measure)-value(a,measure)).slice(0,12).reverse(),teams=aggregate(data,'teamName').sort((a,b)=>value(b,measure)-value(a,measure)).slice(0,12).reverse(),groups=aggregate(data,breakdown).sort((a,b)=>value(b,measure)-value(a,measure)).slice(0,15);
 renderChart('trend-chart','line',yearly,'key',measure,'#d64b32');renderChart('player-chart','bar',players,'key',measure,'#e8ad37',true);renderChart('team-chart','bar',teams,'key',measure,'#102b4e',true);renderChart('breakdown-chart','bar',groups,'key',measure,'#147d7e');$('breakdown-title').textContent=`${labels[measure]} by ${$('breakdown').selectedOptions[0].text.toLowerCase()}`;
 $('data-table').innerHTML=groups.map(x=>`<tr><td>${x.key}</td><td>${x.minYear}${x.maxYear===x.minYear?'':`–${x.maxYear}`}</td><td>${fmt(x.rows)}</td><td>${fmt(x.atBats)}</td><td>${fmt(x.hits)}</td><td>${fmt(x.homeRuns)}</td><td>${fmt(x.runs)}</td><td>${fmt(x.rbi)}</td><td>${fmt(x.stolenBases)}</td><td>${avg(x.hits,x.atBats).toFixed(3)}</td></tr>`).join('')||'<tr><td colspan="10">No rows match these filters.</td></tr>';
}
function reset(){const years=unique('year');$('start-year').value=years[0];$('end-year').value=years.at(-1);$('team').value='all';$('league').value='all';$('player').value='';$('measure').value='homeRuns';$('breakdown').value='teamName';update()}
fetch('data/batting.csv').then(r=>{if(!r.ok)throw Error(`HTTP ${r.status}`);return r.text()}).then(text=>{rows=parseCSV(text);const years=unique('year');fillSelect('start-year',years);fillSelect('end-year',years);fillSelect('team',unique('teamName'),'All teams');fillSelect('league',unique('league'),'All leagues');$('start-year').value=years[0];$('end-year').value=years.at(-1);document.body.classList.remove('loading');document.querySelectorAll('.filters select').forEach(el=>el.addEventListener('change',update));let timer;$('player').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(update,200)});$('reset').addEventListener('click',reset);update()}).catch(err=>{$('status').textContent=`Data could not load: ${err.message}. Serve this folder over HTTP.`});
