const colors={navy:'#102b4e',red:'#d64b32',gold:'#e8ad37',teal:'#147d7e',grid:'rgba(16,43,78,.12)'};
Chart.defaults.font.family='Source Sans 3';Chart.defaults.color='#334155';
const base={responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},title:{display:false}},scales:{x:{grid:{display:false},title:{display:false}},y:{grid:{color:colors.grid},beginAtZero:true,title:{display:false}}}};
const make=(id,type,labels,datasets,options={})=>new Chart(document.getElementById(id),{type,data:{labels,datasets},options:{...base,...options,plugins:{...base.plugins,...options.plugins},scales:{...base.scales,...options.scales}}});
fetch('data/report.json').then(r=>r.json()).then(d=>{
 const dec=d.decadeRates;
 make('chart-power','line',dec.map(x=>x.decade),[{label:'Home runs per 100 at-bats',data:dec.map(x=>x.homeRunsPer100Ab),borderColor:colors.red,backgroundColor:colors.red,tension:.25,pointRadius:4}],{plugins:{legend:{display:true},title:{display:true,text:'Home-run rate by decade'}},scales:{x:{title:{display:true,text:'Decade'}},y:{title:{display:true,text:'Home runs per 100 at-bats'}}}});
 make('chart-discipline','line',dec.map(x=>x.decade),[{label:'Strikeouts per 100 at-bats',data:dec.map(x=>x.strikeoutsPer100Ab),borderColor:colors.navy,tension:.25},{label:'Walks per 100 at-bats',data:dec.map(x=>x.walksPer100Ab),borderColor:colors.gold,tension:.25}],{plugins:{legend:{display:true},title:{display:true,text:'Strikeouts and walks by decade'}},scales:{x:{title:{display:true,text:'Decade'}},y:{title:{display:true,text:'Rate per 100 at-bats'}}}});
 make('chart-average','bar',dec.map(x=>x.decade),[{label:'Batting average',data:dec.map(x=>x.battingAverage),backgroundColor:colors.teal}],{plugins:{title:{display:true,text:'Batting average by decade'}},scales:{x:{title:{display:true,text:'Decade'}},y:{min:.2,max:.3,grid:{color:colors.grid},title:{display:true,text:'Batting average (hits ÷ at-bats)'}}}});
 make('chart-seasons','bar',d.homeRunSeasons.map(x=>x.year),[{label:'Home runs',data:d.homeRunSeasons.map(x=>x.homeRuns),backgroundColor:d.homeRunSeasons.map((_,i)=>i===0?colors.red:colors.gold)}],{plugins:{title:{display:true,text:'Highest single-season home-run totals'}},scales:{x:{title:{display:true,text:'Season'}},y:{title:{display:true,text:'Total home runs'}}}});
 const horizontal=(id,items,label,key,color,title,xTitle)=>make(id,'bar',items.map(x=>x[label]).reverse(),[{label:xTitle,data:items.map(x=>x[key]).reverse(),backgroundColor:color}],{indexAxis:'y',plugins:{title:{display:true,text:title}},scales:{x:{title:{display:true,text:xTitle}},y:{title:{display:true,text:'Player or team'}}}});
 horizontal('chart-career-hr',d.careerHomeRuns,'playerName','homeRuns',colors.red,'Career home-run leaders','Career home runs');
 horizontal('chart-career-avg',d.careerAverage,'playerName','battingAverage',colors.teal,'Qualified career batting-average leaders','Career batting average');
 horizontal('chart-steals',d.careerSteals,'playerName','stolenBases',colors.gold,'Career stolen-base leaders','Career stolen bases');
 horizontal('chart-teams',d.teamHomeRuns.map(x=>({...x,label:`${x.year} ${x.teamName}`})),'label','homeRuns',colors.navy,'Highest team-season home-run totals','Team-season home runs');
}).catch(err=>document.querySelectorAll('.chart-card').forEach(el=>el.innerHTML=`<p>Chart data could not load: ${err.message}</p>`));
